### ISSUE TITLE
Error authenticating admin Immuto account: Password invalid

### ISSUE THREAD

**Issue by jwhelan72** [immuto-inc/webapp_template#1]
The API does not accept my username and password as valid.  I registered and confirmed my email on the Immuto website.

**Comment by SebassCoates** [comment]
Looks like the docs should be more clear here, sorry.  “admin” accounts have more permissions, which are required to run the webapp template. Such an account allows users to register their own accounts through the template. 

I’ll be setting up a sandbox environment with free admin credentials, but for the time being, these should work:
Email: immuto.test@gmail.com
Password: Test12345!

**Comment by jwhelan72** [comment]
That works.

Next error comes when trying to upload a file:

![image](https://user-images.githubusercontent.com/1807284/61156074-e145ce00-a4f2-11e9-8fd2-217e02635f62.png)

I get the same error on your website actually.

**Comment by dr-strauss** [comment]
A certificate expired in our dev environment. Will fix by the end of the day. Thanks for the report!

**Comment by SebassCoates** [comment]
@jwhelan72 Derek was right that a certificate had just expired. It should be fixed now - thanks for your patience!

**Comment by dr-strauss** [comment]
@jwhelan72, have you had a chance to try things out?
